## Modelos Supervisionados

Modelos **supervisionados** são um tipo de técnica de machine learning em que o algoritmo aprende a partir de dados **rotulados**, ou seja, cada exemplo de treinamento possui **entradas** (atributos) e uma **saída** conhecida (rótulo).

Durante o treinamento, o modelo tenta identificar **padrões** que relacionem as entradas com as saídas corretas, ajustando seus parâmetros para **minimizar o erro** entre as previsões feitas e os valores reais. Esse processo permite que o modelo “aprenda” como responder corretamente a novos dados semelhantes aos que ele já viu.

Esse tipo de aprendizado é utilizado em problemas de **classificação** e **regressão**. Na classificação, o objetivo é prever categorias discretas, como identificar se um e-mail é spam ou não. Já na regressão, o foco é prever valores contínuos, como o preço de uma casa ou a temperatura futura.

Alguns tipos básicos são:
- Regressão Linear
- Regressão Logistica
- KNN

---

### Regressão Linear

Regressão Linear é um modelo de aprendizado supervisionado utilizado para prever valores numéricos contínuos. Trata-se de um método simples e interpretável.

Seu objetivo é modelar a relação entre as variáveis de entrada (X) e a variável alvo (y) por meio de uma função linear, ajustando uma reta que melhor se adequa aos dados observados.

A forma básica do modelo, com uma única variável explicativa, é dada por:
$$
y=β0​+β1​x
$$

Quando há múltiplas variáveis de entrada, o modelo assume a forma:
$$
y=β0​+β1​x1​+β2​x2​+⋯+βn​xn​
$$

Onde:
- β1, β2, ... βn representam os coeficientes angulares, que indicam a influência (tendência linear) de cada variável de entrada sobre a saída;
- β0 é o é o intercepto, correspondendo ao valor base de 𝑦 quando todas as variáveis 𝑥 são iguais a zero.

In [30]:
import numpy as np
from sklearn.datasets import fetch_california_housing

data = fetch_california_housing()

X = data.data[:, np.newaxis, 0]  # MedInc (renda média)
y = data.target                  # Valor das Casas

Utilizando o dataset **california_housing** podemos buscar a relação de **Renda Média x Valor das Casas**

In [31]:
X[:10]

array([[8.3252],
       [8.3014],
       [7.2574],
       [5.6431],
       [3.8462],
       [4.0368],
       [3.6591],
       [3.12  ],
       [2.0804],
       [3.6912]])

In [32]:
y[:10]

array([4.526, 3.585, 3.521, 3.413, 3.422, 2.697, 2.992, 2.414, 2.267,
       2.611])

In [40]:
""" Separar o conjunto em treinamento e teste """

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
""" Treinar o modelo """

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

O termo **supervisionado** se refere ao uso de dados **rotulados**, ou seja, exemplos em que os valores de entrada (X) e as saídas (y) já são conhecidas, permitindo que o modelo aprenda essa relação e a utilize para prever resultados para novos dados de entrada.

In [42]:
y_pred[:10]

array([1.14958917, 1.50606882, 1.90393718, 2.85059383, 2.00663318,
       2.42165249, 2.57647226, 1.99229181, 2.45893168, 3.84677436])

**y_pred** corresponde aos valores previstos com base no **X_test**.

In [41]:
""" Exibir os resultados do modelo """

import numpy as np
import plotly.graph_objects as go

# Ordenar valores para desenhar a reta corretamente
idx = np.argsort(X_test.flatten())
X_sorted = X_test.flatten()[idx]
y_pred_sorted = y_pred.flatten()[idx]

# Gráfico interativo
fig = go.Figure()

# Pontos reais
fig.add_trace(go.Scatter(
    x=X_test.flatten(),
    y=y_test,
    mode="markers",
    name="Dados reais",
    marker=dict(color="blue", opacity=0.5)
))

# Reta da regressão
fig.add_trace(go.Scatter(
    x=X_sorted,
    y=y_pred_sorted,
    mode="lines",
    name="Regressão Linear",
    line=dict(color="red", width=3)
))

# Layout
fig.update_layout(
    title="Regressão Linear - California Housing",
    xaxis_title="Renda média",
    yaxis_title="Valor médio das casas",
    template="plotly_white"
)

fig.show()

O modelo indica uma relação **linear positiva**: regiões com maior renda média tendem a apresentar valores médios de casas mais elevados.

Sendo que a inversão desse resultado seria:  
- **linear negativa**: onde quanto maior a renda, menor seria o valor médio das casas.

In [ ]:
""" Avaliar o desempenho do modelo """

from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_pred)
print("Erro Quadrático Médio (MSE):", mse)

Erro Quadrático Médio (MSE): 0.7091157771765549


**MSE** mede o **erro médio** das previsões do modelo, calculando a diferença entre **y_test** do **y_pred**, sendo:  

- Quanto menor o MSE, melhor o modelo.
- MSE = 0 -> previsões perfeitas.

In [ ]:
""" Avaliar o desempenho do modelo """

from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)
print("Erro Absoluto Médio (MAE):", mae)

Erro Absoluto Médio (MAE): 0.629908653009376


Mostra o erro médio e menos sensível a outliers.

In [49]:
""" Avaliar o desempenho do modelo """

from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print("Coeficiente de Determinação (R²):", r2)

Coeficiente de Determinação (R²): 0.45885918903846656


Mostra quanto da variabilidade dos dados o modelo explica, sendo:

- R² = 1 -> perfeito
- R² = 0 -> igual a prever a média
- R² < 0 -> pior que o baseline

### Regressão Logistica

In [35]:
pass

### KNN

In [36]:
pass

### Conclusão

In [ ]:
pass